### ISSUE TITLE
Shift + FN1 (Green) as L_space

### ISSUE THREAD

**Issue by gustavw** [TsFreddie/vortex_mpc_mod#1]
I've been trying to get SHIFT + FN1 to L_SPACE do you think that is even possible?

**Comment by proostas** [comment]
I think you don't need to do that. You can bind a macro containing SHIFT+[any_key] to any other key instead. That is, SHIFT + FN1 + [any_key], becomes Pn + [any_key], for example. Have a look at my config. I'm new to 40% keyboards so I tried to make it as familiar as possible to full-sized keyboard without strange finger acrobatics.

[Vortex Core.txt](https://github.com/TsFreddie/vortex_mpc_mod/files/3278319/Vortex.Core.txt)

**Comment by gustavw** [comment]
Changed the FN layer to Shift + FN1 (Macro, key by key). Since Shift is basically not an layer what I wanted to do doesn't seem possible.
